<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFrameworks>net6.0;net7.0;net8.0</TargetFrameworks>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<PackageId>EfCore.RepositoryPack</PackageId>
		<Version>1.1.5</Version>
		<Authors>Kadir Demirkaya</Authors>
		<Description>Provides a generic repository pattern implementation for Entity Framework Core, supporting all SQL-based databases.</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<RepositoryUrl>https://github.com/kadirdemirkaya/EfCore-Generic-Library</RepositoryUrl>
		<PackageTags>efcore;repository;entityframework;sql;database;dataaccess</PackageTags>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageReleaseNotes>Added support for .NET. Improved performance and fixed minor bugs.</PackageReleaseNotes>
		<AssemblyInformationalVersion>1.1.5</AssemblyInformationalVersion>
		<PackageRequireLicenseAcceptance>false</PackageRequireLicenseAcceptance>
	</PropertyGroup>

	<ItemGroup>
		<None Include="docs\README.md" Pack="true" PackagePath="\" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="EfCore.BaseRepositoryPack" Version="1.1.2" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net6.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="6.0.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net7.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="7.0.0" />
	</ItemGroup>

	<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
		<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.0" />
	</ItemGroup>

</Project>
